---
# Source: hello-world/templates/service.yaml
kind: Service
apiVersion: v1
metadata:
  name: user1-hello-world-service
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: user1-hello-world
---
# Source: hello-world/templates/deployment.yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: user1-hello-world
spec:
  replicas: 3
  selector:
  matchLabels:
    app: user1-hello-world
  template:
    metadata:
      labels:
        app: user1-hello-world
    spec:
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: user1-hello-world
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
          image: quay.io/argo-helm-workshop/workshop-app:v7
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
---
# Source: hello-world/templates/route.yaml
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: user1-hello-world-route
spec:
  to:
    kind: Service
    name:  user1-hello-world-service
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None